# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/instagram_analytics
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Application
spring.application.name=InstagramAnalyticsDashboard

# Instagram Graph API
instagram.business.id=17841447385817456
instagram.page.access.token=EAAXnZCmUoCZB4BSF9KSRmhTNnIwUdDcGNMAA0akBvCZAmc9uChVxzh6atduL8vKlWAVvhZAXqL9HDZBipXdNEPZANmNjpaq0KL18duVllRTkLbrbJx65ZB8yU2jPdyBzfAXzmr4SE1ByTXulrUXAeES9zvCZAxDAxGTnoYEVrwIIZCYZCUOcuDD1wL6UZB01Ghz8ND5ZBvNSIuMWe0o9vUJ2zoxCOe4pombmdbEBw3Oj1QaohVIme0cqkVJ9D5DdD7ZBBhojyKroZC8sZBrD9peXfrWLa9q

# Facebook Graph API
facebook.page.id=1176808755524161
facebook.page.access.token=EAAXnZCmUoCZB4BSKx0asviZCI5bM7wm6DPOmD7oiXzt7znFEeiycQMrQzRkDiEGlCh6BmJfGy93x5cPYfGDOghkjtqOCZBeMOcLRpvpdZCox12NrdpUKk3lXRK1uILZBtSxdJtkCP6IL1AaERnngZC2UwyhE58N7qZBRma2Co5DRwuc3rhBpASpjfHW3ZAGAkxk20HkTw2rZBRFD16tRvgQcHiudZBtfd9ZA4vAVZCQTVf3mKELgZD